/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyMenuPlannerRouteImport } from './routes/weekly-menu-planner'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsRouteImport } from './routes/es'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EsIndexRouteImport } from './routes/es.index'
import { Route as EsWeeklyMenuPlannerRouteImport } from './routes/es.weekly-menu-planner'
import { Route as EsSignupRouteImport } from './routes/es.signup'
import { Route as EsLoginRouteImport } from './routes/es.login'
import { Route as EsAboutRouteImport } from './routes/es.about'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const WeeklyMenuPlannerRoute = WeeklyMenuPlannerRouteImport.update({
  id: '/weekly-menu-planner',
  path: '/weekly-menu-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EsRoute,
} as any)
const EsWeeklyMenuPlannerRoute = EsWeeklyMenuPlannerRouteImport.update({
  id: '/weekly-menu-planner',
  path: '/weekly-menu-planner',
  getParentRoute: () => EsRoute,
} as any)
const EsSignupRoute = EsSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => EsRoute,
} as any)
const EsLoginRoute = EsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => EsRoute,
} as any)
const EsAboutRoute = EsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/es': typeof EsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/weekly-menu-planner': typeof WeeklyMenuPlannerRoute
  '/es/about': typeof EsAboutRoute
  '/es/login': typeof EsLoginRoute
  '/es/signup': typeof EsSignupRoute
  '/es/weekly-menu-planner': typeof EsWeeklyMenuPlannerRoute
  '/es/': typeof EsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/weekly-menu-planner': typeof WeeklyMenuPlannerRoute
  '/es/about': typeof EsAboutRoute
  '/es/login': typeof EsLoginRoute
  '/es/signup': typeof EsSignupRoute
  '/es/weekly-menu-planner': typeof EsWeeklyMenuPlannerRoute
  '/es': typeof EsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/es': typeof EsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/weekly-menu-planner': typeof WeeklyMenuPlannerRoute
  '/es/about': typeof EsAboutRoute
  '/es/login': typeof EsLoginRoute
  '/es/signup': typeof EsSignupRoute
  '/es/weekly-menu-planner': typeof EsWeeklyMenuPlannerRoute
  '/es/': typeof EsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/es'
    | '/login'
    | '/signup'
    | '/weekly-menu-planner'
    | '/es/about'
    | '/es/login'
    | '/es/signup'
    | '/es/weekly-menu-planner'
    | '/es/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/weekly-menu-planner'
    | '/es/about'
    | '/es/login'
    | '/es/signup'
    | '/es/weekly-menu-planner'
    | '/es'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/es'
    | '/login'
    | '/signup'
    | '/weekly-menu-planner'
    | '/es/about'
    | '/es/login'
    | '/es/signup'
    | '/es/weekly-menu-planner'
    | '/es/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EsRoute: typeof EsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  WeeklyMenuPlannerRoute: typeof WeeklyMenuPlannerRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly-menu-planner': {
      id: '/weekly-menu-planner'
      path: '/weekly-menu-planner'
      fullPath: '/weekly-menu-planner'
      preLoaderRoute: typeof WeeklyMenuPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/weekly-menu-planner': {
      id: '/es/weekly-menu-planner'
      path: '/weekly-menu-planner'
      fullPath: '/es/weekly-menu-planner'
      preLoaderRoute: typeof EsWeeklyMenuPlannerRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/signup': {
      id: '/es/signup'
      path: '/signup'
      fullPath: '/es/signup'
      preLoaderRoute: typeof EsSignupRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/login': {
      id: '/es/login'
      path: '/login'
      fullPath: '/es/login'
      preLoaderRoute: typeof EsLoginRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/about': {
      id: '/es/about'
      path: '/about'
      fullPath: '/es/about'
      preLoaderRoute: typeof EsAboutRouteImport
      parentRoute: typeof EsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EsRouteChildren {
  EsAboutRoute: typeof EsAboutRoute
  EsLoginRoute: typeof EsLoginRoute
  EsSignupRoute: typeof EsSignupRoute
  EsWeeklyMenuPlannerRoute: typeof EsWeeklyMenuPlannerRoute
  EsIndexRoute: typeof EsIndexRoute
}

const EsRouteChildren: EsRouteChildren = {
  EsAboutRoute: EsAboutRoute,
  EsLoginRoute: EsLoginRoute,
  EsSignupRoute: EsSignupRoute,
  EsWeeklyMenuPlannerRoute: EsWeeklyMenuPlannerRoute,
  EsIndexRoute: EsIndexRoute,
}

const EsRouteWithChildren = EsRoute._addFileChildren(EsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EsRoute: EsRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  WeeklyMenuPlannerRoute: WeeklyMenuPlannerRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
